### ISSUE TITLE
Doesn't work without equals sign

### ISSUE THREAD

**Issue by FrancisBehnen** [jamy015/slack-latex-bot#3]
I tried posting a message without an "=" character, but it didn't let me.

**Comment by FrancisBehnen** [comment]
Hmm well, nvm I guess. Can’t reproduce. Glitch in the matrix ;)

Met vriendelijke groet,
With kind regards,

Francis Behnen

t: +316 129 509 56
m: francis.behnen@gmail.com <mailto:francis.behnen@gmail.com>

**Comment by jamy015** [comment]
Did this occur at your first usage of the bot after some time? It might be related to a time-out problem (for which I really ought to open an issue).

**Comment by FrancisBehnen** [comment]
Yes

Met vriendelijke groet,
With kind regards,

Francis Behnen

t: +316 129 509 56
m: francis.behnen@gmail.com <mailto:francis.behnen@gmail.com>

**Comment by jamy015** [comment]
Seems like we found the problem :)
