### ISSUE TITLE
'Darn - that slash command didn't work'

### ISSUE THREAD

**Issue by jamy015** [jamy015/slack-latex-bot#6]
Users are getting this error:
<img width="887" alt="screen shot 2017-07-23 at 22 44 13" src="https://user-images.githubusercontent.com/3188721/28502753-9c303ef2-6ff9-11e7-901e-858b99b29c77.png">

It's unclear whether this is the same problem as #5.

**Comment by Fastjur** [comment]
I can confirm that this is related to #5

**Comment by jamy015** [comment]
@Fastjur did you specifically get a timeout error?

**Comment by Fastjur** [comment]
Hmm. Can't say 100% sure, but it did work when retrying after 30 seconds, which is about the startup time from heroku right?

**Comment by jamy015** [comment]
It's hosted on AWS Lambda instead of Heroku now (see https://github.com/jamy015/slack-latex-bot/issues/5#issuecomment-316514430). However, I just checked the AWS console and I can definitely see some spikes above 3000ms (which is the Slack timeout).

![image](https://user-images.githubusercontent.com/3188721/28649847-19ab26d2-7278-11e7-95d9-6821d0596546.png)

Thanks for thinking along @Fastjur!

**Comment by jamy015** [comment]
We have now moved to Elastic Beanstalk. This should have solved this problem. (see 67f3954e7b9bf67c6d5ac314346cb6513d588ef1)
